import { createFileRoute } from "@tanstack/react-router";
import { useHistory } from "@/hooks/useSalaryQueries";
import { HistoryTable } from "@/components/history/HistoryTable";

export const Route = createFileRoute("/history")({
  head: () => ({
    meta: [
      { title: "Prediction History — SalarySense AI" },
      {
        name: "description",
        content:
          "Search and filter every salary prediction by job title, department and city, with predicted salary and status.",
      },
      { property: "og:title", content: "Prediction History — SalarySense AI" },
      {
        property: "og:description",
        content: "A searchable log of every ML salary prediction generated in your workspace.",
      },
    ],
  }),
  component: HistoryPage,
});

function HistoryPage() {
  const history = useHistory();

  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">
          Prediction <span className="text-gradient">History</span>
        </h1>
        <p className="mt-2 max-w-2xl text-muted-foreground">
          Every prediction generated by the model, searchable by job title or department and
          filterable by department and city.
        </p>
      </header>

      <HistoryTable records={history.data} isLoading={history.isLoading} />
    </div>
  );
}
