import { Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { formatUsd, type HistoryRecord } from "@/api/salaryApi";
import { Badge } from "@/components/ui/badge";
import { LoadingSkeleton } from "@/components/LoadingSkeleton";

const DEPARTMENT_TONE: Record<string, string> = {
  Engineering: "border-primary/40 bg-primary/10 text-primary",
  "Data Science": "border-accent/40 bg-accent/10 text-accent",
  Product: "border-chart-3/40 bg-chart-3/10 text-chart-3",
  Design: "border-chart-5/40 bg-chart-5/10 text-chart-5",
  Marketing: "border-chart-4/40 bg-chart-4/10 text-chart-4",
};

export function DepartmentBadge({ department }: { department: string }) {
  return (
    <Badge
      variant="outline"
      className={DEPARTMENT_TONE[department] ?? "border-border bg-secondary/60 text-muted-foreground"}
    >
      {department}
    </Badge>
  );
}

interface RecentPredictionsProps {
  records: HistoryRecord[] | undefined;
  isLoading: boolean;
}

export function RecentPredictions({ records, isLoading }: RecentPredictionsProps) {
  return (
    <section className="glass rounded-3xl p-5 sm:p-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-lg font-semibold tracking-tight">Recent predictions</h2>
          <p className="text-sm text-muted-foreground">Latest salary estimates generated by the model.</p>
        </div>
        <Link
          to="/history"
          className="inline-flex items-center gap-1 text-sm font-medium text-primary transition-colors hover:text-accent"
        >
          View all history <ArrowUpRight className="size-4" />
        </Link>
      </div>

      <div className="mt-5 overflow-x-auto">
        {isLoading ? (
          <div className="space-y-2">
            {Array.from({ length: 5 }).map((_, i) => (
              <LoadingSkeleton key={i} className="h-12" />
            ))}
          </div>
        ) : (
          <table className="w-full min-w-[640px] text-sm">
            <thead>
              <tr className="border-b border-border/60 text-left text-xs uppercase tracking-wide text-muted-foreground">
                <th className="pb-3 font-medium">Date</th>
                <th className="pb-3 font-medium">Job title</th>
                <th className="pb-3 font-medium">Department</th>
                <th className="pb-3 font-medium">Experience</th>
                <th className="pb-3 text-right font-medium">Predicted salary</th>
              </tr>
            </thead>
            <tbody>
              {(records ?? []).slice(0, 6).map((r) => (
                <tr
                  key={r.id}
                  className="border-b border-border/40 transition-colors last:border-0 hover:bg-secondary/40"
                >
                  <td className="py-3 text-muted-foreground">
                    {new Date(r.created_at).toLocaleDateString("en-US", {
                      month: "short",
                      day: "numeric",
                      year: "numeric",
                    })}
                  </td>
                  <td className="py-3 font-medium">{r.job_title}</td>
                  <td className="py-3">
                    <DepartmentBadge department={r.department} />
                  </td>
                  <td className="py-3 text-muted-foreground">{r.experience} yrs</td>
                  <td className="py-3 text-right font-semibold text-accent">
                    {formatUsd(r.predicted_salary)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </section>
  );
}
